"""OCAP processing endpoint."""
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, Depends
from pydantic import BaseModel
from app.services.ocap_service import OCAPService
from app.core.dependencies import get_logger, get_current_active_user
from app.models.user import User
import logging

router = APIRouter()


class RegistryMatch(BaseModel):
    """Registry match model."""
    node_type: str  # style, operation, defect, or error
    value: str  # The matched value from registry
    match_type: str  # exact or partial
    confidence: int  # 0-100


class QueryRequest(BaseModel):
    """Request model for OCAP query."""
    query: str
    thread_id: Optional[str] = None  # Optional thread ID for conversation context


class QueryResponse(BaseModel):
    """Response model for OCAP query."""
    query: str
    thread_id: Optional[str]
    workflow_run_id: Optional[str] = None  # Unique ID for this workflow execution (for tracing)
    keywords: List[str]
    registry_matches: List[RegistryMatch]
    query_spec_summary: str
    thread_memory_summary: str
    classification: Optional[str] = None  # Query classification (precise, error-precise, non-precise, generic)
    classify_formatted_text: Optional[str] = None  # Pretty-printed Elasticsearch results for LLM context
    response: Optional[str] = None  # Final summary response generated by summarize node
    status: str
    message: str


@router.post("/process", response_model=QueryResponse)
async def process_query(
    request: QueryRequest,
    current_user: User = Depends(get_current_active_user),
    logger: logging.Logger = Depends(get_logger)
):
    """
    Process an OCAP query.
    
    Requires authentication via JWT token.
    
    Args:
        request: Query request containing the user query and optional thread_id
        current_user: Current authenticated user
        logger: Logger instance
        
    Returns:
        Processed query response
    """
    logger.info(
        f"Received query from user {current_user.username} "
        f"(user_id: {current_user.id}): {request.query[:50]}..."
    )
    
    service = OCAPService()
    result = service.process_query(
        query=request.query,
        thread_id=request.thread_id,
        user_id=current_user.id
    )
    
    return QueryResponse(**result)

