"""OCAP processing endpoint."""
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, Depends, UploadFile, File, HTTPException
from pydantic import BaseModel
from app.services.ocap_service import OCAPService
from app.services.index_service import IndexService
from app.core.dependencies import get_logger, get_current_active_user
from app.models.user import User
import logging
import tempfile
import os

router = APIRouter()


class RegistryMatch(BaseModel):
    """Registry match model."""
    node_type: str  # style, operation, defect, or error
    value: str  # The matched value from registry
    match_type: str  # exact or partial
    confidence: int  # 0-100


class QueryRequest(BaseModel):
    """Request model for OCAP query."""
    query: str
    thread_id: Optional[str] = None  # Optional thread ID for conversation context


class QueryResponse(BaseModel):
    """Response model for OCAP query."""
    query: str
    thread_id: Optional[str]
    workflow_run_id: Optional[str] = None  # Unique ID for this workflow execution (for tracing)
    keywords: List[str]
    registry_matches: List[RegistryMatch]
    query_spec_summary: str
    thread_memory_summary: str
    classification: Optional[str] = None  # Query classification (precise, error-precise, non-precise, generic)
    classify_formatted_text: Optional[str] = None  # Pretty-printed Elasticsearch results for LLM context
    response: Optional[str] = None  # Final summary response generated by summarize node
    status: str
    message: str


class IndexCreationResponse(BaseModel):
    """Response model for index creation."""
    status: str
    message: str
    fact_index: str
    relationship_index: str
    records_processed: int


@router.post("/process", response_model=QueryResponse)
async def process_query(
    request: QueryRequest,
    current_user: User = Depends(get_current_active_user),
    logger: logging.Logger = Depends(get_logger)
):
    """
    Process an OCAP query.
    
    Requires authentication via JWT token.
    
    Args:
        request: Query request containing the user query and optional thread_id
        current_user: Current authenticated user
        logger: Logger instance
        
    Returns:
        Processed query response
    """
    logger.info(
        f"Received query from user {current_user.username} "
        f"(user_id: {current_user.id}): {request.query[:50]}..."
    )
    
    service = OCAPService()
    result = service.process_query(
        query=request.query,
        thread_id=request.thread_id,
        user_id=current_user.id
    )
    
    return QueryResponse(**result)


@router.post("/create-index", response_model=IndexCreationResponse)
async def create_index(
    file: UploadFile = File(..., description="XLSX file to create indexes from"),
    current_user: User = Depends(get_current_active_user),
    logger: logging.Logger = Depends(get_logger)
):
    """
    Create Elasticsearch indexes from an uploaded XLSX file.
    
    This endpoint:
    1. Reads the XLSX file
    2. Transforms and cleans the data
    3. Creates the fact layer index (ocap-knowledge-base)
    4. Creates the relationship index (ocap-relationship-index)
    
    Requires authentication via JWT token.
    
    Args:
        file: XLSX file containing OCAP data with columns: Style, Defect, Operation, Error, Action
        current_user: Current authenticated user
        logger: Logger instance
        
    Returns:
        Index creation response with status and details
    """
    # Validate file type
    if not file.filename.endswith(('.xlsx', '.xls')):
        raise HTTPException(
            status_code=400,
            detail="File must be an Excel file (.xlsx or .xls)"
        )
    
    logger.info(
        f"Received index creation request from user {current_user.username} "
        f"(user_id: {current_user.id}) for file: {file.filename}"
    )
    
    # Save uploaded file to temporary location
    temp_file = None
    try:
        # Create temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix='.xlsx') as tmp:
            temp_file = tmp.name
            # Read file content
            content = await file.read()
            tmp.write(content)
        
        # Create indexes using the service
        service = IndexService()
        result = service.create_indexes_from_excel(temp_file)
        
        logger.info(
            f"Indexes created successfully by user {current_user.username}. "
            f"Fact index: {result['fact_index']}, "
            f"Relationship index: {result['relationship_index']}, "
            f"Records processed: {result['records_processed']}"
        )
        
        return IndexCreationResponse(**result)
        
    except Exception as e:
        logger.error(f"Error creating indexes: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error creating indexes: {str(e)}"
        )
    finally:
        # Clean up temporary file
        if temp_file and os.path.exists(temp_file):
            try:
                os.unlink(temp_file)
            except Exception as e:
                logger.warning(f"Failed to delete temporary file {temp_file}: {e}")

